In [1]:
import pandas as pd
books = pd.read_csv("books_with_categories.csv")

In [2]:
from transformers import pipeline
classifier = pipeline("text-classification", model="j-hartmann/emotion-english-distilroberta-base", top_k = None)
classifier("I love this!")

Device set to use cpu

[[{'label': 'joy', 'score': 0.9771687984466553},
  {'label': 'surprise', 'score': 0.008528673090040684},
  {'label': 'neutral', 'score': 0.005764589179307222},
  {'label': 'anger', 'score': 0.004419779404997826},
  {'label': 'sadness', 'score': 0.002092391485348344},
  {'label': 'disgust', 'score': 0.0016119909705594182},
  {'label': 'fear', 'score': 0.00041385178337804973}]]

In [3]:
books["description"][0]

'A NOVEL THAT READERS and critics have been eagerly anticipating for over a decade, Gilead is an astonishingly imagined story of remarkable lives. John Ames is a preacher, the son of a preacher and the grandson (both maternal and paternal) of preachers. It’s 1956 in Gilead, Iowa, towards the end of the Reverend Ames’s life, and he is absorbed in recording his family’s story, a legacy for the young son he will never see grow up. Haunted by his grandfather’s presence, John tells of the rift between his grandfather and his father: the elder, an angry visionary who fought for the abolitionist cause, and his son, an ardent pacifist. He is troubled, too, by his prodigal namesake, Jack (John Ames) Boughton, his best friend’s lost son who returns to Gilead searching for forgiveness and redemption. Told in John Ames’s joyous, rambling voice that finds beauty, humour and truth in the smallest of life’s details, Gilead is a song of celebration and acceptance of the best and the worst the world has to offer. At its heart is a tale of the sacred bonds between fathers and sons, pitch-perfect in style and story, set to dazzle critics and readers alike.'

In [4]:
classifier(books["description"][0])

[[{'label': 'fear', 'score': 0.6548418998718262},
  {'label': 'neutral', 'score': 0.16985182464122772},
  {'label': 'sadness', 'score': 0.11640854179859161},
  {'label': 'surprise', 'score': 0.020700592547655106},
  {'label': 'disgust', 'score': 0.01910073682665825},
  {'label': 'joy', 'score': 0.015161239542067051},
  {'label': 'anger', 'score': 0.00393515033647418}]]

In [5]:
#ranking emotion based on EACH sentence
classifier(books["description"][0].split("."))

[[{'label': 'surprise', 'score': 0.7296027541160583},
  {'label': 'neutral', 'score': 0.14038576185703278},
  {'label': 'fear', 'score': 0.06816209107637405},
  {'label': 'joy', 'score': 0.04794240742921829},
  {'label': 'anger', 'score': 0.00915635284036398},
  {'label': 'disgust', 'score': 0.0026284719351679087},
  {'label': 'sadness', 'score': 0.0021221607457846403}],
 [{'label': 'neutral', 'score': 0.449370414018631},
  {'label': 'disgust', 'score': 0.27359241247177124},
  {'label': 'joy', 'score': 0.10908260941505432},
  {'label': 'sadness', 'score': 0.09362703561782837},
  {'label': 'anger', 'score': 0.040478307753801346},
  {'label': 'surprise', 'score': 0.02697017230093479},
  {'label': 'fear', 'score': 0.006879065651446581}],
 [{'label': 'neutral', 'score': 0.6462168097496033},
  {'label': 'sadness', 'score': 0.2427326887845993},
  {'label': 'disgust', 'score': 0.04342268034815788},
  {'label': 'surprise', 'score': 0.028300466015934944},
  {'label': 'joy', 'score': 0.014211482368409634},
  {'label': 'fear', 'score': 0.014084089547395706},
  {'label': 'anger', 'score': 0.011031883768737316}],
 [{'label': 'fear', 'score': 0.928168535232544},
  {'label': 'anger', 'score': 0.0321907103061676},
  {'label': 'neutral', 'score': 0.012808633036911488},
  {'label': 'sadness', 'score': 0.00875683594495058},
  {'label': 'surprise', 'score': 0.008597894571721554},
  {'label': 'disgust', 'score': 0.008431794121861458},
  {'label': 'joy', 'score': 0.0010455806041136384}],
 [{'label': 'sadness', 'score': 0.9671575427055359},
  {'label': 'neutral', 'score': 0.015104170888662338},
  {'label': 'disgust', 'score': 0.006480592768639326},
  {'label': 'fear', 'score': 0.005393994972109795},
  {'label': 'surprise', 'score': 0.0022869433742016554},
  {'label': 'anger', 'score': 0.0018428886542096734},
  {'label': 'joy', 'score': 0.001733880490064621}],
 [{'label': 'joy', 'score': 0.9327982664108276},
  {'label': 'disgust', 'score': 0.03771686181426048},
  {'label': 'neutral', 'score': 0.015891842544078827},
  {'label': 'sadness', 'score': 0.006444473285228014},
  {'label': 'anger', 'score': 0.005024951882660389},
  {'label': 'surprise', 'score': 0.0015812074998393655},
  {'label': 'fear', 'score': 0.0005423047696240246}],
 [{'label': 'joy', 'score': 0.6528704166412354},
  {'label': 'neutral', 'score': 0.254274845123291},
  {'label': 'surprise', 'score': 0.06808319687843323},
  {'label': 'sadness', 'score': 0.009908993728458881},
  {'label': 'disgust', 'score': 0.00651219068095088},
  {'label': 'anger', 'score': 0.004821313079446554},
  {'label': 'fear', 'score': 0.003529015462845564}],
 [{'label': 'neutral', 'score': 0.5494767427444458},
  {'label': 'sadness', 'score': 0.11169015616178513},
  {'label': 'disgust', 'score': 0.10400672256946564},
  {'label': 'surprise', 'score': 0.07876548916101456},
  {'label': 'anger', 'score': 0.06413363665342331},
  {'label': 'fear', 'score': 0.05136279761791229},
  {'label': 'joy', 'score': 0.040564414113759995}]]

In [6]:
sentences= books["description"][0].split(".")
predictions = classifier(sentences)

In [7]:
sentences[0]

'A NOVEL THAT READERS and critics have been eagerly anticipating for over a decade, Gilead is an astonishingly imagined story of remarkable lives'

In [8]:
predictions[0]

[{'label': 'surprise', 'score': 0.7296027541160583},
 {'label': 'neutral', 'score': 0.14038576185703278},
 {'label': 'fear', 'score': 0.06816209107637405},
 {'label': 'joy', 'score': 0.04794240742921829},
 {'label': 'anger', 'score': 0.00915635284036398},
 {'label': 'disgust', 'score': 0.0026284719351679087},
 {'label': 'sadness', 'score': 0.0021221607457846403}]

In [9]:
sentences[3]

' Haunted by his grandfather’s presence, John tells of the rift between his grandfather and his father: the elder, an angry visionary who fought for the abolitionist cause, and his son, an ardent pacifist'

In [10]:
predictions[3]

[{'label': 'fear', 'score': 0.928168535232544},
 {'label': 'anger', 'score': 0.0321907103061676},
 {'label': 'neutral', 'score': 0.012808633036911488},
 {'label': 'sadness', 'score': 0.00875683594495058},
 {'label': 'surprise', 'score': 0.008597894571721554},
 {'label': 'disgust', 'score': 0.008431794121861458},
 {'label': 'joy', 'score': 0.0010455806041136384}]

In [11]:
sorted(predictions[0], key=lambda x: x["label"])

[{'label': 'anger', 'score': 0.00915635284036398},
 {'label': 'disgust', 'score': 0.0026284719351679087},
 {'label': 'fear', 'score': 0.06816209107637405},
 {'label': 'joy', 'score': 0.04794240742921829},
 {'label': 'neutral', 'score': 0.14038576185703278},
 {'label': 'sadness', 'score': 0.0021221607457846403},
 {'label': 'surprise', 'score': 0.7296027541160583}]

In [21]:
import numpy as np

emotion_labels = ["anger", "disgust", "fear", "joy", "sadness", "surprise", "neutral"]
isbn = []
emotion_scores = {label: [] for label in emotion_labels}

def calculate_max_emotion_scores(predictions):
    per_emotion_scores = {label: [] for label in emotion_labels}
    for prediction in predictions:
        sorted_predictions = sorted(prediction, key=lambda x: x["label"])
        for index, label in enumerate(emotion_labels):
            per_emotion_scores[label].append(sorted_predictions[index]["score"])
    return {label: np.max(scores) for label, scores in per_emotion_scores.items()}

In [22]:

for i in range(10):
    isbn.append(books["isbn13"][i])
    sentences = books["description"][i].split(".")
    predictions = classifier(sentences)
    max_scores = calculate_max_emotion_scores(predictions)
    for label in emotion_labels:
        emotion_scores[label].append(max_scores[label])

In [25]:
emotions_df = pd.DataFrame(emotion_scores)
emotions_df["isbn13"] = isbn

In [26]:
emotions_df

,anger,disgust,fear,joy,sadness,surprise,neutral,isbn13
0,0.064134,0.273592,0.928169,0.932798,0.646217,0.967158,0.729603,9780002005883
1,0.612619,0.348284,0.942528,0.704422,0.887939,0.111690,0.252545,9780002261982
2,0.064134,0.104007,0.972321,0.767237,0.549477,0.111690,0.078765,9780006178736
3,0.351483,0.150723,0.360707,0.251881,0.732685,0.111690,0.078765,9780006280897
4,0.081412,0.184495,0.095043,0.040564,0.884390,0.475881,0.078765,9780006280934
5,0.232225,0.727174,0.051363,0.043376,0.621393,0.111690,0.271903,9780006380832
6,0.538184,0.155855,0.747428,0.872565,0.712195,0.408000,0.078765,9780006470229
7,0.064134,0.104007,0.404498,0.040564,0.549477,0.820282,0.234487,9780006472612
8,0.300669,0.279481,0.915524,0.040564,0.840290,0.354461,0.135615,9780006482079
9,0.064134,0.177927,0.051363,0.040564,0.860372,0.111690,0.078765,9780006483014

In [27]:
books = pd.merge(books, emotions_df, on="isbn13")

In [29]:
books

,isbn13,isbn10,title,authors,categories,thumbnail,description,published_year,average_rating,num_pages,...,simple_categories,predicted_categories_x,predicted_categories_y,anger,disgust,fear,joy,sadness,surprise,neutral
0,9780002005883,0002005883,Gilead,Marilynne Robinson,Fiction,http://books.google.com/books/content?id=KQZCP...,A NOVEL THAT READERS and critics have been eag...,2004.0,3.85,247.0,...,Fiction,NaN,NaN,0.064134,0.273592,0.928169,0.932798,0.646217,0.967158,0.729603
1,9780002261982,0002261987,Spider's Web,Charles Osborne;Agatha Christie,Detective and mystery stories,http://books.google.com/books/content?id=gA5GP...,A new 'Christie for Christmas' -- a full-lengt...,2000.0,3.83,241.0,...,Fiction,Fiction,Fiction,0.612619,0.348284,0.942528,0.704422,0.887939,0.111690,0.252545
2,9780006178736,0006178731,Rage of angels,Sidney Sheldon,Fiction,http://books.google.com/books/content?id=FKo2T...,"A memorable, mesmerizing heroine Jennifer -- b...",1993.0,3.93,512.0,...,Fiction,NaN,NaN,0.064134,0.104007,0.972321,0.767237,0.549477,0.111690,0.078765
3,9780006280897,0006280897,The Four Loves,Clive Staples Lewis,Christian life,http://books.google.com/books/content?id=XhQ5X...,Lewis' work on the nature of love divides love...,2002.0,4.15,170.0,...,Nonfiction,Nonfiction,Nonfiction,0.351483,0.150723,0.360707,0.251881,0.732685,0.111690,0.078765
4,9780006280934,0006280935,The Problem of Pain,Clive Staples Lewis,Christian life,http://books.google.com/books/content?id=Kk-uV...,"""In The Problem of Pain, C.S. Lewis, one of th...",2002.0,4.09,176.0,...,Nonfiction,Nonfiction,Nonfiction,0.081412,0.184495,0.095043,0.040564,0.884390,0.475881,0.078765
5,9780006380832,0006380832,Empires of the Monsoon,Richard Hall,"Africa, East",http://books.google.com/books/content?id=MuPEQ...,Until Vasco da Gama discovered the sea-route t...,1998.0,4.41,608.0,...,Nonfiction,Nonfiction,Nonfiction,0.232225,0.727174,0.051363,0.043376,0.621393,0.111690,0.271903
6,9780006470229,000647022X,The Gap Into Madness,Stephen R. Donaldson,"Hyland, Morn (Fictitious character)",http://books.google.com/books/content?id=4oXav...,A new-cover reissue of the fourth book in the ...,1994.0,4.15,743.0,...,Fiction,Fiction,Fiction,0.538184,0.155855,0.747428,0.872565,0.712195,0.408000,0.078765
7,9780006472612,0006472613,Master of the Game,Sidney Sheldon,Adventure stories,http://books.google.com/books/content?id=TkTYp...,Kate Blackwell is an enigma and one of the mos...,1982.0,4.11,489.0,...,Nonfiction,Nonfiction,Nonfiction,0.064134,0.104007,0.404498,0.040564,0.549477,0.820282,0.234487
8,9780006482079,0006482074,Warhost of Vastmark,Janny Wurts,Fiction,http://books.google.com/books/content?id=uOL0f...,"Tricked once more by his wily half-brother, Ly...",1995.0,4.03,522.0,...,Fiction,NaN,NaN,0.300669,0.279481,0.915524,0.040564,0.840290,0.354461,0.135615
9,9780006483014,0006483011,The Once and Future King,Terence Hanbury White,Arthurian romances,http://books.google.com/books/content?id=Jx6Bv...,An omnibus volume of the author's complete sto...,1996.0,4.04,823.0,...,Fiction,Fiction,Fiction,0.064134,0.177927,0.051363,0.040564,0.860372,0.111690,0.078765

In [30]:
books.to_csv("books_with_emotions.csv", index = False)